### ISSUE TITLE
Update Oomph setup file to load content from Github

### ISSUE THREAD

**Issue by ujhelyiz** [eclipse-viatra/org.eclipse.viatra#150]
The Oomph setup files got broken after the migration to Github (e.g. it sets up a wrong Git repository and changes are not anymore fetched by the central registry).

**Comment by bergmanngabor** [comment]
FWIW I have run an Oomph setup today to see where we stand now. 

Feedback:
- I had to manually specify the Oomph parameter for the CI base address as https://ci.eclipse.org/viatra/job/VIATRA/job/master
  * ... and I have to supply it again and again every time I run Setup Tasks 
- RCPTT should be installed by Oomph - otherwise I am immediately prompted to do something about this unsupported project nature
- A few build errors: (sample)
  * The project was not built since its build path is incomplete. Cannot find the class file for com.sun.jdi.StackFrame. Fix the build path then try building this project	org.eclipse.viatra.query.tooling.debug		Unknown	Java Problem
  * An active annotation used in this file was compiled against a different version of Xtend than the one that is currently installed.
    * This one, unfortunately, seems to break vital parts of the query development UI

But the progress really looks promising, keep up the good work!

**Comment by ujhelyiz** [comment]
Most likely I will only continue to work on this after #152 will be merged, as the dependency changes will require another set of updates, and at that point will I plan finalize this. However, thanks for the feedback.

**Comment by bergmanngabor** [comment]
> the target platform was updated to SimRel 2020-06

Actually, it seems to be more like 2020-12. Corroborating this, I have found after bumping my Eclipse IDE to 2020-12 that the Xtend version inconsistency errors do indeed disappear (not the other problems).

**Comment by ujhelyiz** [comment]
>> the target platform was updated to SimRel 2020-06

> Actually, it seems to be more like 2020-12. Corroborating this, I have found after bumping my Eclipse IDE to 2020-12 that the Xtend version inconsistency errors do indeed disappear (not the other problems).

The base target platform everything has to compile against is 2020-06; you can use Oomph to install VIATRA with the current platform, e.g. I am using it with 2024-03. It is possible I have messed up something with older versions, but I really don't plan to fix those before merging the new minimum dependency versions (that would change things greatly).

On the other hand, thinking about the issue you mentioned here I found that the VIATRA Tooling configuration was not correct. I don't usually use that configuration so issues might fall through the cracks here. I tried to update the given URL as necessary. @bergmanngabor Could you test whether this has fixed (at least some) of the issues?

**Comment by bergmanngabor** [comment]
Pulling the newest setup file and re-running the setup, I see P2 Director complaining: 
> Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0:  https://ci.eclipse.org/viatra/job/VIATRA/job/master/lastSuccessfulBuild/artifact/releng/org.eclipse.viatra.update/target/repository
