### ISSUE TITLE
Code generation silently fails if the project name contains spaces

### ISSUE THREAD

**Issue by KocsisV** [eclipse-viatra/org.eclipse.viatra#154]
In eclipse if the project name contains spaces then the code generation from the VQL files silently fails, nothing is generated. No entry gets added to the problems, nor the error log.
Renaming the project to something without spaces solves the issue.

**Comment by ujhelyiz** [comment]
Question for clarification: by project name you mean the folder name the project is in, the UI-only project name or both (by default, they are the same, but they don't have to be).

**Comment by KocsisV** [comment]
The UI only project name, which might not be the same as the folder name you said.

**Comment by bergmanngabor** [comment]
https://github.com/eclipse-viatra/org.eclipse.viatra/blob/cb120e7d84fe7352686a312c4f7a39f51b9eb930/query/plugins/org.eclipse.viatra.query.patternlanguage.emf.ui/src/org/eclipse/viatra/query/patternlanguage/emf/ui/builder/EMFPatternLanguageBuilderParticipant.java#L124

I think this is it. We compare the project name to the delta URI, without encoding the project name to be URI-compliant. The URI will have `%20` instead of ` ` regular space characters.
